// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Logger is the predicate function for logger builders.
type Logger func(*sql.Selector)
