// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// Machine is the predicate function for machine builders.
type Machine func(*sql.Selector)
