// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "creator", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Default: ""},
		{Name: "spec", Type: field.TypeString, Default: ""},
		{Name: "comment", Type: field.TypeString, Default: ""},
		{Name: "updater", Type: field.TypeString, Default: ""},
		{Name: "method", Type: field.TypeString, Default: "GET"},
		{Name: "body", Type: field.TypeString, Default: ""},
		{Name: "header", Type: field.TypeString, Default: ""},
		{Name: "count", Type: field.TypeInt},
		{Name: "retry", Type: field.TypeInt},
		{Name: "retry_temp", Type: field.TypeInt},
		{Name: "status", Type: field.TypeInt},
		{Name: "ctime", Type: field.TypeTime, Nullable: true},
		{Name: "mtime", Type: field.TypeTime, Nullable: true},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:        "jobs",
		Columns:     JobsColumns,
		PrimaryKey:  []*schema.Column{JobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// MachinesColumns holds the columns for the "machines" table.
	MachinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "host", Type: field.TypeString, Default: ""},
		{Name: "port", Type: field.TypeInt},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "password", Type: field.TypeString, Default: ""},
		{Name: "comment", Type: field.TypeString, Default: ""},
		{Name: "command", Type: field.TypeString, Default: ""},
		{Name: "creator", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeInt},
		{Name: "ctime", Type: field.TypeTime, Nullable: true},
		{Name: "mtime", Type: field.TypeTime, Nullable: true},
	}
	// MachinesTable holds the schema information for the "machines" table.
	MachinesTable = &schema.Table{
		Name:        "machines",
		Columns:     MachinesColumns,
		PrimaryKey:  []*schema.Column{MachinesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		JobsTable,
		MachinesTable,
	}
)

func init() {
}
