// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api2.proto

/*
Package userapi is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api2.proto
*/
package userapi

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathTokenVerifyVerify = "/user.v2.TokenVerify/Verify"

// TokenVerifyBMServer is the server API for TokenVerify service.
type TokenVerifyBMServer interface {
	Verify(ctx context.Context, req *VerifyReq) (resp *VerifyReply, err error)
}

var TokenVerifySvc TokenVerifyBMServer

func tokenVerifyVerify(c *bm.Context) {
	p := new(VerifyReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := TokenVerifySvc.Verify(c, p)
	c.JSON(resp, err)
}

// RegisterTokenVerifyBMServer Register the blademaster route
func RegisterTokenVerifyBMServer(e *bm.Engine, server TokenVerifyBMServer) {
	TokenVerifySvc = server
	e.GET("/user.v2.TokenVerify/Verify", tokenVerifyVerify)
}
