// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: cron_logger.proto

/*
Package cron_log_v1 is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	cron_logger.proto
*/
package cron_log_v1

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathCronLoggerWriteLog = "/cron.logger.v1.CronLogger/WriteLog"

// CronLoggerBMServer is the server API for CronLogger service.
type CronLoggerBMServer interface {
	WriteLog(ctx context.Context, req *WriteLogReq) (resp *NoReply, err error)
}

var CronLoggerSvc CronLoggerBMServer

func cronLoggerWriteLog(c *bm.Context) {
	p := new(WriteLogReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := CronLoggerSvc.WriteLog(c, p)
	c.JSON(resp, err)
}

// RegisterCronLoggerBMServer Register the blademaster route
func RegisterCronLoggerBMServer(e *bm.Engine, server CronLoggerBMServer) {
	CronLoggerSvc = server
	e.GET("/cron.logger.v1.CronLogger/WriteLog", cronLoggerWriteLog)
}
