// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// LoggersColumns holds the columns for the "loggers" table.
	LoggersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "log", Type: field.TypeString, Default: ""},
		{Name: "operator", Type: field.TypeString, Default: ""},
		{Name: "ctime", Type: field.TypeTime, Nullable: true},
	}
	// LoggersTable holds the schema information for the "loggers" table.
	LoggersTable = &schema.Table{
		Name:        "loggers",
		Columns:     LoggersColumns,
		PrimaryKey:  []*schema.Column{LoggersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LoggersTable,
	}
)

func init() {
}
