// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"way-jasy-cron/cron-logger/internal/model/ent/migrate"

	"way-jasy-cron/cron-logger/internal/model/ent/logger"

	"github.com/facebook/ent/dialect"
	"github.com/facebook/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Logger is the client for interacting with the Logger builders.
	Logger *LoggerClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Logger = NewLoggerClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Logger: NewLoggerClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config: cfg,
		Logger: NewLoggerClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Logger.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Logger.Use(hooks...)
}

// LoggerClient is a client for the Logger schema.
type LoggerClient struct {
	config
}

// NewLoggerClient returns a client for the Logger from the given config.
func NewLoggerClient(c config) *LoggerClient {
	return &LoggerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `logger.Hooks(f(g(h())))`.
func (c *LoggerClient) Use(hooks ...Hook) {
	c.hooks.Logger = append(c.hooks.Logger, hooks...)
}

// Create returns a create builder for Logger.
func (c *LoggerClient) Create() *LoggerCreate {
	mutation := newLoggerMutation(c.config, OpCreate)
	return &LoggerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Logger entities.
func (c *LoggerClient) CreateBulk(builders ...*LoggerCreate) *LoggerCreateBulk {
	return &LoggerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Logger.
func (c *LoggerClient) Update() *LoggerUpdate {
	mutation := newLoggerMutation(c.config, OpUpdate)
	return &LoggerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LoggerClient) UpdateOne(l *Logger) *LoggerUpdateOne {
	mutation := newLoggerMutation(c.config, OpUpdateOne, withLogger(l))
	return &LoggerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LoggerClient) UpdateOneID(id int) *LoggerUpdateOne {
	mutation := newLoggerMutation(c.config, OpUpdateOne, withLoggerID(id))
	return &LoggerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Logger.
func (c *LoggerClient) Delete() *LoggerDelete {
	mutation := newLoggerMutation(c.config, OpDelete)
	return &LoggerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *LoggerClient) DeleteOne(l *Logger) *LoggerDeleteOne {
	return c.DeleteOneID(l.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *LoggerClient) DeleteOneID(id int) *LoggerDeleteOne {
	builder := c.Delete().Where(logger.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LoggerDeleteOne{builder}
}

// Query returns a query builder for Logger.
func (c *LoggerClient) Query() *LoggerQuery {
	return &LoggerQuery{config: c.config}
}

// Get returns a Logger entity by its id.
func (c *LoggerClient) Get(ctx context.Context, id int) (*Logger, error) {
	return c.Query().Where(logger.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LoggerClient) GetX(ctx context.Context, id int) *Logger {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LoggerClient) Hooks() []Hook {
	return c.hooks.Logger
}
