// Code generated by entc, DO NOT EDIT.

package ent

import (
	"way-jasy-cron/cron-logger/internal/model/ent/logger"
	"way-jasy-cron/cron-logger/internal/model/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	loggerFields := schema.Logger{}.Fields()
	_ = loggerFields
	// loggerDescLog is the schema descriptor for log field.
	loggerDescLog := loggerFields[1].Descriptor()
	// logger.DefaultLog holds the default value on creation for the log field.
	logger.DefaultLog = loggerDescLog.Default.(string)
	// loggerDescOperator is the schema descriptor for operator field.
	loggerDescOperator := loggerFields[2].Descriptor()
	// logger.DefaultOperator holds the default value on creation for the operator field.
	logger.DefaultOperator = loggerDescOperator.Default.(string)
	// loggerDescID is the schema descriptor for id field.
	loggerDescID := loggerFields[0].Descriptor()
	// logger.IDValidator is a validator for the "id" field. It is called by the builders before save.
	logger.IDValidator = loggerDescID.Validators[0].(func(int) error)
}
