// Code generated by entc, DO NOT EDIT.

package logger

const (
	// Label holds the string label denoting the logger type in the database.
	Label = "logger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLog holds the string denoting the log field in the database.
	FieldLog = "log"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldCtime holds the string denoting the ctime field in the database.
	FieldCtime = "ctime"

	// Table holds the table name of the logger in the database.
	Table = "loggers"
)

// Columns holds all SQL columns for logger fields.
var Columns = []string{
	FieldID,
	FieldLog,
	FieldOperator,
	FieldCtime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLog holds the default value on creation for the "log" field.
	DefaultLog string
	// DefaultOperator holds the default value on creation for the "operator" field.
	DefaultOperator string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)
