// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: cron.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	cron.proto
*/
package api

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathJobWriteLog = "/cron.v1.Job/WriteLog"
var PathJobVerify = "/cron.v1.Job/Verify"

// JobBMServer is the server API for Job service.
type JobBMServer interface {
	WriteLog(ctx context.Context, req *WriteLogReq) (resp *NoReply, err error)

	Verify(ctx context.Context, req *VerifyReq) (resp *VerifyReply, err error)
}

var JobSvc JobBMServer

func jobWriteLog(c *bm.Context) {
	p := new(WriteLogReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := JobSvc.WriteLog(c, p)
	c.JSON(resp, err)
}

func jobVerify(c *bm.Context) {
	p := new(VerifyReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := JobSvc.Verify(c, p)
	c.JSON(resp, err)
}

// RegisterJobBMServer Register the blademaster route
func RegisterJobBMServer(e *bm.Engine, server JobBMServer) {
	JobSvc = server
	e.GET("/cron.v1.Job/WriteLog", jobWriteLog)
	e.GET("/cron.v1.Job/Verify", jobVerify)
}
