FROM golang:latest

MAINTAINER WayJasy 306698601@qq.com

ENV GO111MODULE on
ENV CGO_ENABLED 0
ENV GOPROXY https://goproxy.cn

RUN mkdir -p /go/app

WORKDIR /go/app

ADD . /go/app

RUN cd /go/app/user/cmd && go build main.go

EXPOSE 8001
EXPOSE 9001

ENTRYPOINT ["./user/cmd/main", "-conf=./user/configs"]


